# Generated by Django 2.2 on 2019-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('RUB', 'Russian Ruble')], max_length=10)),
            ],
        ),
    ]
